"""Utility functions for plotting functionality.

This module provides helper functions for creating, saving, and displaying
plots generated during research workflows.
"""

import logging
import pathlib
from typing import Callable, Dict, List, Optional, Tuple

import jax.numpy as jnp
import matplotlib.pyplot as plt
import seaborn as sns
from matplotlib.patches import Patch

from io_handlers import (
    read_blosc,
)
from plots_functions import NoPlotDataError, get_plot_function


def plot_from_data_dump(
    filename: str,
    figsize: Tuple[int, int] = (8, 6),
    title: Optional[str] = None,
    xlabel: Optional[str] = None,
    ylabel: Optional[str] = None,
) -> None:
    """Plot data from a dumped plot data file.

    Load stored plot data from a .dat file and display it with
    optional custom labels and title.

    Parameters
    ----------
    filename : str
        Name of the plot data file (without .dat extension).
    figsize : Tuple[int, int], optional
        Figure size as (width, height). Default is (8, 6).
    title : Optional[str], optional
        Plot title. Default is None.
    xlabel : Optional[str], optional
        X-axis label. Default is None.
    ylabel : Optional[str], optional
        Y-axis label. Default is None.

    Raises
    ------
    FileNotFoundError
        If the plot data file does not exist.
    """
    current_path = pathlib.Path(__file__).parent.resolve()
    project_root = current_path.parent
    plot_data_path = project_root / "output" / "plot_data"

    # Sanitize the filename
    filename = filename.replace(".dat", "")
    plot_data_file = plot_data_path / f"{filename}.dat"
    if not plot_data_file.exists():
        raise FileNotFoundError(f"Plot data file {plot_data_file} not found.")

    data = read_blosc(plot_data_file)
    x_axis = data["x"]
    data.pop("x")

    fig, ax = plt.subplots(figsize=figsize)
    for series_name, y_axis in data.items():
        ax.plot(x_axis, y_axis, label=series_name)

    if title is not None:
        ax.set_title(title)

    if xlabel is not None:
        ax.set_xlabel(xlabel)

    if ylabel is not None:
        ax.set_ylabel(ylabel)

    ax.legend()
    plt.tight_layout()
    plt.show()


def run_plot_jobs(
    title: str,
    target_dof: int,
    jobs: Dict[str, Dict[str, object]],
) -> None:
    """Execute a set of plot jobs.

    Iterate through each job in the dictionary and execute the
    corresponding plot function with the given parameters.

    Parameters
    ----------
    title : str
        Title for the plot, also used as filename/output name.
    target_dof : int
        Target degrees of freedom, passed if the function
        signature includes this parameter.
    jobs : Dict[str, Dict[str, object]]
        Dictionary of plot jobs. Each key is a plot function
        name, and each value is a dictionary of parameters.

    Raises
    ------
    ValueError
        If the specified plot function is not found.
    TypeError
        If job parameters are not a dictionary.
    """
    from inspect import signature

    for entry in jobs:
        plot_func_name = list(entry.keys())[0]
        params = list(entry.values())[0]
        logging.info(f"Running plot job: {plot_func_name}...")

        plot_fn = get_plot_function(plot_func_name)
        if not callable(plot_fn):
            raise ValueError(
                f"Plot function `{plot_func_name}` not found in this module."
            )
        if not isinstance(params, dict):
            raise TypeError(f"Job parameters for `{plot_func_name}` must be a dict.")

        fn_params = signature(plot_fn).parameters

        # Positional args
        pos_args = [title]
        if "target_dof" in fn_params:
            pos_args.append(target_dof)

        # Take everything from the dict as-is (no sorting)
        # Do not pass 'ax' from config
        call_kwargs = {}
        for k, v in params.items():
            if k == "__arg_order__":
                continue
            if k == "ax":
                # Never allow external ax
                continue
            # Ignore kwarg if target_dof already passed positionally
            if k == "target_dof":
                continue
            # Allow 'title' kwarg for the plotting function
            call_kwargs[k] = v

        filename = f"{plot_func_name}_{title}"

        save_plots(
            *pos_args,
            filename=filename,
            plot_function=plot_fn,
            call_kwargs=call_kwargs,
        )
        logging.info(f"Saved plot for {plot_func_name}")


def save_plots(
    *args,
    filename: str,
    plot_function: Callable,
    figsize: Tuple[int, int] = (10, 8),
    call_kwargs: Optional[Dict[str, object]] = None,
) -> None:
    """Save a plot generated by plot_function.

    Automatically detect whether the plot function accepts an
    axes parameter and create one if needed. Save the resulting
    figure as a PDF file in the output/plots directory.

    Parameters
    ----------
    *args
        Positional arguments passed to the plot function.
    filename : str
        Name of the output file (without extension).
    plot_function : Callable
        The plotting function to execute.
    figsize : Tuple[int, int], optional
        Figure size as (width, height). Default is (10, 8).
    call_kwargs : Optional[Dict[str, object]], optional
        Additional keyword arguments for the plot function.
    """
    from inspect import signature

    from matplotlib.axes import Axes
    from matplotlib.figure import Figure

    current_path = pathlib.Path(__file__).parent.resolve()
    project_root = current_path.parent
    plot_path = project_root / "output" / "plots"
    plot_path.mkdir(parents=True, exist_ok=True)
    filepath = plot_path / f"{filename}.pdf"

    plt.ioff()

    # Unwrap decorators to inspect the real signature
    fn = plot_function
    while hasattr(fn, "__wrapped__"):
        fn = fn.__wrapped__
    sig = signature(fn)

    kw = dict(call_kwargs or {})
    created_fig = None

    # Supply 'ax' if function accepts it and we don't have one
    if "ax" in sig.parameters and "ax" not in kw:
        created_fig, ax = plt.subplots(figsize=figsize)
        kw["ax"] = ax

    try:
        # Call the plotting function and capture the return value
        ret = plot_function(*args, **kw)
    except NoPlotDataError as e:
        logging.warning(f"No plot data. {e}")
        return

    # Determine which figure to use
    if isinstance(ret, Figure):
        used_fig = ret
    elif isinstance(ret, tuple) and ret and isinstance(ret[0], Figure):
        used_fig = ret[0]
    elif isinstance(ret, Axes):
        used_fig = ret.figure
    elif created_fig is not None:
        used_fig = created_fig
    else:
        used_fig = plt.gcf()

    used_fig.savefig(str(filepath), bbox_inches="tight")

    try:
        plt.close(used_fig)
    finally:
        if created_fig is not None and created_fig is not used_fig:
            plt.close(created_fig)

    plt.ion()


def plot_ensemble_energy_data_with_reference(
    data_dir: str,
    maximum_displacement: float,
    reference_data_file: Optional[str] = None,
    figsize: Tuple[int, int] = (8, 6),
    title: Optional[str] = None,
) -> None:
    """Plot statistics of energies from an ensemble of models.

    Load energy data files from the specified directory, compute
    mean and standard deviation, and plot with optional reference
    data comparison.

    Parameters
    ----------
    data_dir : str
        Directory containing plot energy data files.
    maximum_displacement : float
        Maximum displacement value for the x-axis.
    reference_data_file : Optional[str], optional
        Path to reference data file for comparison. Default is None.
    figsize : Tuple[int, int], optional
        Figure size as (width, height). Default is (8, 6).
    title : Optional[str], optional
        Plot title. Default is None.

    Raises
    ------
    FileNotFoundError
        If no matching data files are found in the directory.
    """
    # Retrieve the data files
    data_files = list(pathlib.Path(data_dir).glob("*__plot_energy.dat")) or list(
        pathlib.Path(data_dir).glob("stream_plot_energy*.dat")
    )
    if not data_files:
        raise FileNotFoundError(
            f"No data files found in {data_dir} matching '*__plot_energy.dat' nor 'stream_plot_energy*.dat'."
        )
    data = [read_blosc(f) for f in data_files]
    predictions_data = {k: [] for k in data[0].keys()}
    for entry in data:
        for k, v in entry.items():
            predictions_data[k].append(v)

    # Form the displacement vector for predictions
    displacement_array_predictions = jnp.linspace(
        0, maximum_displacement, len(predictions_data["x"][0])
    )
    predictions_data.pop("x")

    # Compute mean and standard deviation
    for key in list(predictions_data.keys()):
        predictions_data[f"{key}_mean"] = jnp.mean(
            jnp.array(predictions_data[key]), axis=0
        )
        predictions_data[f"{key}_std"] = jnp.std(
            jnp.array(predictions_data[key]), axis=0
        )
        predictions_data.pop(key)

    # Begin plotting the predictions
    fig, ax = plt.subplots(figsize=figsize)
    for key in predictions_data.keys():
        if "mean" in key:
            label = key.replace("_mean", " DRM")
            ax.plot(displacement_array_predictions, predictions_data[key], label=label)
            std_key = key.replace("mean", "std")
            ax.fill_between(
                displacement_array_predictions,
                predictions_data[key] - predictions_data[std_key],
                predictions_data[key] + predictions_data[std_key],
                alpha=0.3,
            )

    # Plot the reference data if provided
    reference_data = read_blosc(reference_data_file)
    if reference_data is not None:
        displacement_array_reference = jnp.linspace(
            0, maximum_displacement, len(reference_data["x"])
        )
        reference_data.pop("x")
        for key in reference_data.keys():
            ax.plot(
                displacement_array_reference,
                reference_data[key],
                label=f"{key} FEM",
                linestyle="--",
            )

    label_size = 16
    tick_size = 14
    # Apply formatting
    ax.set_xlabel("Displacement, m", fontsize=label_size)
    ax.set_ylabel("Energy, J", fontsize=label_size)
    ax.set_xlim(0, maximum_displacement)
    ax.set_ylim(bottom=0)

    if title:
        ax.set_title(title)
    ax.legend(fontsize=tick_size)
    ax.tick_params(axis="both", which="major", labelsize=tick_size)
    plt.grid()


def plot_energy_convergence(
    data_dirs: List[Tuple[str, str]],
    maximum_displacement: float,
    reference_data_file: Optional[str] = None,
    figsize: Tuple[int, int] = (8, 4),
    energy_key: str = "elastic_energy",
    xlabel: Optional[str] = None,
) -> None:
    """Plot the convergence of energy predictions across multiple models.

    Compare energy predictions from different model directories
    against reference data, showing mean absolute error and
    standard deviation as grouped bar charts.

    Parameters
    ----------
    data_dirs : List[Tuple[str, str]]
        List of (directory_path, display_label) tuples for each
        set of models to compare.
    maximum_displacement : float
        Maximum displacement value for the x-axis.
    reference_data_file : Optional[str], optional
        Path to reference data file for comparison. Default is None.
    figsize : Tuple[int, int], optional
        Figure size as (width, height). Default is (8, 4).
    energy_key : str, optional
        Key for the energy data to plot. Default is "elastic_energy".
    xlabel : Optional[str], optional
        Custom x-axis label. Default is None.
    """

    palette = sns.color_palette("dark")
    label_size = 16
    tick_size = 14

    ref_interp = None
    if reference_data_file is not None:
        reference_data = read_blosc(reference_data_file)
        if energy_key in reference_data:
            n_ref = len(reference_data[energy_key])
            disp_ref = jnp.linspace(0, maximum_displacement, n_ref)
            ref_values = jnp.array(reference_data[energy_key])
            ref_interp = (disp_ref, ref_values)

    labels = []
    mean_errors = []
    mean_stds = []

    for i, (data_dir, dir_label) in enumerate(data_dirs):
        data_files = list(pathlib.Path(data_dir).glob("*__plot_energy.dat"))
        if not data_files:
            continue
        data = [read_blosc(f) for f in data_files]
        raw_values = jnp.array([entry[energy_key] for entry in data])
        n_points = raw_values.shape[1]
        displacement = jnp.linspace(0, maximum_displacement, n_points)
        mean = jnp.mean(raw_values, axis=0)
        std = jnp.std(raw_values, axis=0)

        mask = displacement > 0
        mean_std = jnp.mean(std[mask])

        if ref_interp is not None:
            disp_ref, ref_values = ref_interp
            ref_on_grid = jnp.interp(displacement, disp_ref, ref_values)
            errors = raw_values - ref_on_grid[None, :]
            mean_error = jnp.mean(jnp.abs(errors[:, mask]))
            mean_std = jnp.mean(jnp.std(jnp.abs(errors[:, mask]), axis=0))
        else:
            mean_error = 0.0

        labels.append(dir_label)
        mean_errors.append(float(mean_error))
        mean_stds.append(float(mean_std))

    x = jnp.arange(len(labels))
    width = 0.35

    fig, ax = plt.subplots(figsize=figsize)

    for i in range(len(labels)):
        color = palette[i % len(palette)]
        ax.bar(
            x[i] - width / 2,
            mean_errors[i],
            width,
            color=color,
            edgecolor="black",
            linewidth=0.8,
        )
        ax.bar(
            x[i] + width / 2,
            mean_stds[i],
            width,
            color=color,
            edgecolor="black",
            linewidth=0.8,
            alpha=0.5,
        )

    legend_handles = [
        Patch(facecolor="grey", edgecolor="black", linewidth=0.8, label="Mean |error|"),
        Patch(
            facecolor="grey",
            edgecolor="black",
            linewidth=0.8,
            alpha=0.5,
            label="Mean std of |error|",
        ),
    ]
    ax.legend(handles=legend_handles, fontsize=tick_size - 1)
    pretty_name = energy_key.replace("_", " ").capitalize()
    ax.set_ylabel("Energy, J", fontsize=label_size)
    if xlabel is not None:
        ax.set_xlabel(xlabel, fontsize=label_size)
    ax.set_title(pretty_name, fontsize=label_size + 1)
    ax.set_xticks(x)
    ax.set_xticklabels(labels, fontsize=tick_size)
    ax.tick_params(axis="y", which="major", labelsize=tick_size)
    ax.grid(True, alpha=0.3, axis="y")

    plt.tight_layout()
